version: "2.2"
services:
  kibana:
    container_name: kibana
    image: kibana:7.12.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic_net

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.12.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic_net

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic_net: